// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_PiCWaWP48D0G8c9JE6gJYxpwWEZCR6E',
    appId: '1:632362869394:web:3d0f45695505562e4abc4b',
    messagingSenderId: '632362869394',
    projectId: 'studio-1376979708-27870',
    authDomain: 'studio-1376979708-27870.firebaseapp.com',
    storageBucket: 'studio-1376979708-27870.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFcvN10-cWgjZ-wDL-2czC_qOD-ZIR68',
    appId: '1:632362869394:android:7d55ce3132fe9f454abc4b',
    messagingSenderId: '632362869394',
    projectId: 'studio-1376979708-27870',
    storageBucket: 'studio-1376979708-27870.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMxY6L1hOWTcIRL0A8f1dR0CKOBQjgaXw',
    appId: '1:632362869394:ios:7a471b8e934d5f704abc4b',
    messagingSenderId: '632362869394',
    projectId: 'studio-1376979708-27870',
    storageBucket: 'studio-1376979708-27870.firebasestorage.app',
    iosBundleId: 'com.example.chdAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMxY6L1hOWTcIRL0A8f1dR0CKOBQjgaXw',
    appId: '1:632362869394:ios:7a471b8e934d5f704abc4b',
    messagingSenderId: '632362869394',
    projectId: 'studio-1376979708-27870',
    storageBucket: 'studio-1376979708-27870.firebasestorage.app',
    iosBundleId: 'com.example.chdAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_PiCWaWP48D0G8c9JE6gJYxpwWEZCR6E',
    appId: '1:632362869394:web:aea4128e47f108d14abc4b',
    messagingSenderId: '632362869394',
    projectId: 'studio-1376979708-27870',
    authDomain: 'studio-1376979708-27870.firebaseapp.com',
    storageBucket: 'studio-1376979708-27870.firebasestorage.app',
  );
}
